import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Legend,
  Line,
  LineChart,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';
import {
  FaCheckDouble,
  FaBell,
  FaBroadcastTower,
  FaBullhorn,
  FaChartBar,
  FaChalkboardTeacher,
  FaDownload,
  FaEllipsisV,
  FaCheckSquare,
  FaSearch,
  FaTrash,
  FaPaperPlane,
  FaPaperclip,
  FaPlus,
  FaSchool,
  FaSignOutAlt,
  FaSpinner,
  FaMicrophone,
  FaStopCircle,
  FaAddressCard,
  FaTimes,
  FaUserGraduate,
  FaUsers,
  FaMoneyBillWave,
} from 'react-icons/fa';
import { toast } from 'react-toastify';
import useSocket from '../../hooks/useSocket';
import { useAuth } from '../../context/useAuth';
import API from '../../api/axiosInstance';
import logo from '../../assets/logo.png';
import StatCard from '../../components/Dashboard/StatCard';
import UserTable from '../../components/Tables/UserTable';
import AnnouncementForm from '../../components/Announcements/AnnouncementForm';
import AnnouncementList from '../../components/Announcements/AnnouncementList';
import ChatModal from '../../components/chat/ChatModal';
import { openAdminReportPrintWindow } from '../../utils/adminReportPrint';
import { resolveMediaUrl } from '../../utils/media';
import { fileToDataUrl, prepareUploadFile } from '../../utils/uploadMedia';
import { createOptimisticMessage, releaseOptimisticMedia } from '../../utils/chatMessage';
import { getCache, setCache, CACHE_KEYS } from '../../utils/localStorageCache';
import './adminPanel.css';

const CHART_COLORS = ['#2563eb', '#0f766e', '#ea580c', '#7c3aed', '#db2777', '#14b8a6'];

const emptyForm = {
  name: '',
  email: '',
  password: '',
  role: 'student',
  class_id: '',
  bio: '',
  profile_image: '',
};

const defaultTemplate = {
  schoolName: 'EduFlow',
  reportTitle: 'Administrative Performance Report',
  principalName: 'Principal Office',
  preparedBy: 'Admin Dashboard',
  accentColor: '#2563eb',
  footerNote: 'This report was generated By School Admin.',
};

const formatCurrency = (value) =>
  new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'PKR',
    maximumFractionDigits: 0,
  }).format(Number(value || 0));

const isImage = (url = '') => /\.(jpg|jpeg|png|gif|webp|svg|heic|heif)(?:\?.*)?$/i.test(url) || url.startsWith('blob:') || url.startsWith('data:image/');
const isVideo = (url = '') => /\.(mp4|webm|ogg)(?:\?.*)?$/i.test(url) || url.startsWith('blob:') || url.startsWith('data:video/');
const isAudio = (url = '') => /\.(mp3|wav|m4a|aac|ogg|webm|opus)(?:\?.*)?$/i.test(url) || url.startsWith('blob:') || url.startsWith('data:audio/');

const formatDateTime = (value) => {
  if (!value) return 'N/A';
  return new Date(value).toLocaleString();
};

const stripNotificationTags = (message = '') =>
  String(message)
    .replace(/\[(requestId|salaryId|tx):[^\]]+\]/gi, '')
    .replace(/\s{2,}/g, ' ')
    .trim();

const extractTaggedId = (message, tag) => {
  const match = String(message || '').match(new RegExp(`\\[${tag}:(\\d+)\\]`, 'i'));
  return match ? Number(match[1]) : null;
};

const AdminDashboard = () => {
  const { user, logout } = useAuth();
  const navigate = useNavigate();

  const [dashboard, setDashboard] = useState(null);
  const [announcements, setAnnouncements] = useState([]);
  const [loading, setLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [notifications, setNotifications] = useState([]);
  const [showNotifications, setShowNotifications] = useState(false);
  const [feePaymentRequests, setFeePaymentRequests] = useState([]);
  const [feeRequestModal, setFeeRequestModal] = useState({ open: false, request: null, remarks: '', saving: false });
  const [activeClassId, setActiveClassId] = useState('');
  const [showUserForm, setShowUserForm] = useState(false);
  const [showClassForm, setShowClassForm] = useState(false);
  const [editingUser, setEditingUser] = useState(null);
  const [formData, setFormData] = useState(emptyForm);
  const [editingAnnouncement, setEditingAnnouncement] = useState(null);
  const [classFormData, setClassFormData] = useState({ grade_level: '', section: '' });
  const [imagePreview, setImagePreview] = useState(null);
  const [isRecording, setIsRecording] = useState(false);
  const [showAdminChatModal, setShowAdminChatModal] = useState(false);
  const [selectedChatUser, setSelectedChatUser] = useState(null);
  const [adminChatMessages, setAdminChatMessages] = useState([]);
  const [adminNewMessage, setAdminNewMessage] = useState('');
  const [adminSelectedFile, setAdminSelectedFile] = useState(null);
  const [broadcastData, setBroadcastData] = useState({ class_id: '', message: '' });
  const [subscriptionRequestModal, setSubscriptionRequestModal] = useState({
    open: false,
    duration: '1month',
    price: '',
    file: null,
    loading: false,
    screenshotPreview: null,
  });
  const [reportTemplate, setReportTemplate] = useState(defaultTemplate);
  const [unreadMessages, setUnreadMessages] = useState({});
  const [isTyping, setIsTyping] = useState(false);
  const [userSearch, setUserSearch] = useState('');
  const [userPage, setUserPage] = useState(1);
  const [totalUsers, setTotalUsers] = useState(0);
  const userLimit = 10;
  const [loadingChat, setLoadingChat] = useState(false);
  const [chatHasMore, setChatHasMore] = useState(false);
  const [chatCursor, setChatCursor] = useState(null);
  const [selectedMessages, setSelectedMessages] = useState([]);
  const [selectionMode, setSelectionMode] = useState(false);
  const [deleteModal, setDeleteModal] = useState({ show: false, ids: [], canDeleteEveryone: false });
  const [savingUser, setSavingUser] = useState(false);
  const [savingClass, setSavingClass] = useState(false);
  const [sendingAdminMessage, setSendingAdminMessage] = useState(false);
  const [sendingBroadcast, setSendingBroadcast] = useState(false);
  const unreadCount = notifications.filter(n => !n.is_read).length;

  const chatMessagesRef = useRef(null);
  const adminFileInputRef = useRef(null);
  const typingTimeoutRef = useRef(null);
  const mediaRecorderRef = useRef(null);
  const recordedChunksRef = useRef([]);
  const socket = useSocket(user?.id);

  const fetchAdminNotifications = useCallback(async () => {
    try {
      const res = await API.get('/admin/notifications');
      setNotifications(res.data.notifications || []);
    } catch {
      // ignore: admin dashboard should still work
    }
  }, []);

  const fetchFeePaymentRequests = useCallback(async () => {
    try {
      const res = await API.get('/fees/payment-requests', { params: { status: 'pending' } });
      setFeePaymentRequests(res.data.requests || []);
    } catch {
      // ignore
    }
  }, []);

  const openFeeRequestModal = useCallback(async (requestId, fallbackRequest = null) => {
    if (!requestId && !fallbackRequest?.id) {
      toast.error('Fee payment request details were not found');
      return;
    }

    const localRequest =
      fallbackRequest ||
      feePaymentRequests.find((item) => Number(item.id) === Number(requestId)) ||
      null;

    if (localRequest) {
      setFeeRequestModal({ open: true, request: localRequest, remarks: localRequest.remarks || '', saving: false });
    }

    try {
      const res = await API.get('/fees/payment-requests', { params: { status: 'pending' } });
      const pendingRequests = res.data.requests || [];
      setFeePaymentRequests(pendingRequests);

      const request =
        pendingRequests.find((item) => Number(item.id) === Number(requestId || fallbackRequest?.id)) ||
        localRequest;

      if (!request) {
        toast.error('This fee payment request is no longer pending');
        return;
      }

      setFeeRequestModal({ open: true, request, remarks: request.remarks || '', saving: false });
    } catch (error) {
      if (!localRequest) {
        toast.error(error.response?.data?.message || 'Failed to load fee payment request');
      }
    }
  }, [feePaymentRequests]);

  const handleSubscriptionFileChange = async (event) => {
    const file = event.target.files?.[0] || null;
    if (!file) return;

    try {
      const preparedFile = await prepareUploadFile(file, { maxBytes: 5 * 1024 * 1024, maxSizeMB: 1.5 });
      setSubscriptionRequestModal((prev) => ({
        ...prev,
        file: preparedFile,
        screenshotPreview: URL.createObjectURL(preparedFile),
      }));
    } catch (error) {
      toast.error(error.message || 'Screenshot must be under 5MB');
      event.target.value = '';
    }
  };

  const submitSubscriptionRequest = async (event) => {
    event.preventDefault();
    if (!subscriptionRequestModal.duration || !subscriptionRequestModal.price) {
      toast.error('Please choose duration and enter a price');
      return;
    }

    setSubscriptionRequestModal((prev) => ({ ...prev, loading: true }));
    try {
      const formData = new FormData();
      formData.append('duration', subscriptionRequestModal.duration);
      formData.append('price', subscriptionRequestModal.price);
      if (subscriptionRequestModal.file) {
        formData.append('file', subscriptionRequestModal.file);
      }

      await API.post('/admin/subscription-requests', formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });

      toast.success('Subscription request sent to Super Admin');
      setSubscriptionRequestModal({
        open: false,
        duration: '1month',
        price: '',
        file: null,
        loading: false,
        screenshotPreview: null,
      });
    } catch (error) {
      toast.error(error.response?.data?.message || 'Failed to send subscription request');
      setSubscriptionRequestModal((prev) => ({ ...prev, loading: false }));
    }
  };

  const classes = useMemo(() => dashboard?.classes || [], [dashboard?.classes]);
  const users = useMemo(() => dashboard?.users || [], [dashboard?.users]);
  const summary = dashboard?.summary || {
    totalStudents: 0,
    totalTeachers: 0,
    totalClasses: 0,
    totalAnnouncements: 0,
  };

  useEffect(() => {
    if (!dashboard?.school?.name) return;

    setReportTemplate((prev) => {
      if (prev.schoolName && prev.schoolName !== defaultTemplate.schoolName) {
        return prev;
      }

      return {
        ...prev,
        schoolName: dashboard.school.name,
      };
    });
  }, [dashboard?.school?.name]);

  const teachers = useMemo(() => {
    return users.filter(u => u.role === 'teacher');
  }, [users]);

  const selectedClassLabel = useMemo(() => {
    const active = classes.find((item) => String(item.id) === String(activeClassId));
    return active?.name || 'All classes';
  }, [activeClassId, classes]);

  const initialDashboardLoad = useRef(false);

  const loadDashboard = useCallback(async (classId = activeClassId, page = userPage, search = userSearch, silent = false) => {
    // 1. Try Loading from Cache first for immediate UI response
    const cacheKey = CACHE_KEYS.ADMIN_DASHBOARD(`${user.school_id}_${classId}_${page}`);
    const cached = getCache(cacheKey);
    if (cached && !silent && cached.analytics) {
      setDashboard(cached.analytics);
      if (cached.analytics.totalUsersCount) {
        setTotalUsers(cached.analytics.totalUsersCount);
      }
      setLoading(false); // Hide initial loader
    }

    if (!silent) setLoading(true);
    else setIsRefreshing(true);
    try {
      const params = {
        classId: classId || undefined,
        page,
        limit: userLimit,
        search: search || undefined
      };
      let dashboardRes;
      let announcementsRes;

      if (silent) {
        dashboardRes = await API.get('/admin/dashboard', { params });
      } else {
        [dashboardRes, announcementsRes] = await Promise.all([
          API.get('/admin/dashboard', { params }),
          API.get('/announcements'),
        ]);
      }

      const freshData = dashboardRes.data;
      setDashboard(freshData.analytics);
      setTotalUsers(freshData.analytics.totalUsersCount || 0);
      
      if (announcementsRes) {
        setAnnouncements(announcementsRes.data.announcements || []);
      }

      // 2. Update Cache
      setCache(cacheKey, freshData);

      setBroadcastData((prev) => ({
        ...prev,
        class_id: classId || '',
      }));
    } catch (error) {
      toast.error(error.response?.data?.message || 'Failed to load admin dashboard');
    } finally {
      setLoading(false);
      setIsRefreshing(false);
    }
  }, [activeClassId, userLimit, userPage, userSearch]);

  useEffect(() => {
    if (!user?.id) return;

    if (!initialDashboardLoad.current) {
      initialDashboardLoad.current = true;
      loadDashboard(activeClassId, 1, userSearch);
      setUserPage(1);
      fetchAdminNotifications();
      fetchFeePaymentRequests();
      return;
    }

    const delayDebounceFn = setTimeout(() => {
      loadDashboard(activeClassId, 1, userSearch, true);
      setUserPage(1);
    }, 300);

    return () => clearTimeout(delayDebounceFn);
  }, [userSearch, activeClassId, user?.id, fetchAdminNotifications, fetchFeePaymentRequests, loadDashboard]);
  

  useEffect(() => {
    if (!socket || !user?.id) return;

    socket.emit('join', user.id);
    socket.emit('joinAdmins'); // Ensure admin joins the system room for broadcast updates

    // Listen for dashboard updates from server instead of polling every 30s
    socket.on('dashboardDataUpdate', () => {
      loadDashboard(activeClassId, userPage, userSearch, true);
    });

    const handleReceiveMessage = (message) => {
      const senderId = Number(message.sender_id || message.senderId);
      const receiverId = Number(message.receiver_id || message.receiverId);

      const isCurrentConversation = selectedChatUser && (
        (senderId === Number(selectedChatUser.id) && receiverId === Number(user?.id)) ||
        (senderId === Number(user?.id) && receiverId === Number(selectedChatUser.id))
      );

      if (isCurrentConversation) {
        setAdminChatMessages((prev) => {
          if (prev.some(m => m.id === message.id)) return prev;
          return [...prev, message];
        });

        // If the chat is open and we are receiving a message from the contact, mark as seen
        if (showAdminChatModal && senderId === Number(selectedChatUser.id)) {
          socket.emit("markSeen", { senderId, receiverId: user.id, messageIds: [message.id] });
        }
      } else if (receiverId === Number(user.id)) {
        // Update unread count badge for specific user in the user list
        setUnreadMessages(prev => ({
          ...prev,
          [senderId]: (prev[senderId] || 0) + 1
        }));
      }
    };

    const handleUserStatusUpdate = ({ userId, online, last_seen }) => {
      setDashboard((prev) => {
        if (!prev) return prev;
        return {
          ...prev,
          users: prev.users.map((item) =>
            Number(item.id) === Number(userId) ? { ...item, online, last_seen } : item
          ),
        };
      });

      // Pro Fix: Keep the chat header in sync with live status
      setSelectedChatUser((prev) => {
        if (prev && Number(prev.id) === Number(userId)) {
          return { ...prev, online, last_seen };
        }
        return prev;
      });
    };

    const handleTyping = ({ senderId }) => {
      if (Number(selectedChatUser?.id) !== Number(senderId)) return;
      setIsTyping(true);
      clearTimeout(typingTimeoutRef.current);
      typingTimeoutRef.current = setTimeout(() => setIsTyping(false), 2000);
    };

    const markMessagesAsSeenLocally = (senderId) => {
      setAdminChatMessages((prev) =>
        prev.map((msg) =>
          Number(msg.sender_id) === Number(senderId) && msg.status !== "seen"
            ? { ...msg, status: "seen" }
            : msg
        )
      );
    };

    const handleMessagesSeen = ({ receiverId, messageIds }) => {
      if (Number(receiverId) !== Number(user?.id)) return;
      setAdminChatMessages((prev) =>
        prev.map((msg) =>
          (messageIds?.length
            ? messageIds.includes(msg.id)
            : Number(msg.receiver_id) === Number(receiverId) && Number(msg.sender_id) === Number(user?.id))
            ? { ...msg, status: "seen" }
            : msg
        )
      );
    };

    const handleNewNotification = (notif) => {
      setNotifications((prev) => {
        if (prev.some((n) => n.id === notif.id)) return prev;
        return [notif, ...prev];
      });

      if (notif?.type === 'fee_payment_request') {
        fetchFeePaymentRequests();
        const requestId = extractTaggedId(notif.message, 'requestId');
        toast.info(
          <div style={{ minWidth: 300 }}>
            <div style={{ fontWeight: 800, marginBottom: 6 }}>{notif.title || 'Fee payment request'}</div>
            <div style={{ fontSize: 13, opacity: 0.9, marginBottom: 10 }}>
              {stripNotificationTags(notif.message)}
            </div>
            <button
              className="btn btn-success"
              onClick={() => openFeeRequestModal(requestId)}
            >
              Review
            </button>
          </div>,
          { autoClose: false, closeOnClick: false, draggable: false }
        );
      }

      if (notif?.type === 'salary_approved') {
        toast.success(
          <div style={{ minWidth: 280 }}>
            <div style={{ fontWeight: 700, marginBottom: 6 }}>{notif.title || 'Salary approval'}</div>
            <div style={{ fontSize: 13, opacity: 0.9 }}>
              {stripNotificationTags(notif.message)}
            </div>
          </div>,
          { autoClose: 7000 }
        );
      }

      if (['salary_approved', 'salary_rejected', 'subscription_update', 'subscription_approved', 'subscription_rejected'].includes(notif?.type)) {
        loadDashboard(activeClassId);
      }
    };

    const handleMessagesDeleted = ({ messageIds }) => {
      setAdminChatMessages((prev) =>
        prev.map((msg) =>
          messageIds.includes(msg.id)
            ? { ...msg, message: "🚫 This message was deleted", file_url: null, deleted: true }
            : msg
        )
      );
      setSelectedMessages([]);
      setSelectionMode(false);
      toast.info("A message was deleted in this conversation");
    };

    socket.on('receiveMessage', handleReceiveMessage);
    socket.on('userStatusUpdate', handleUserStatusUpdate);
    socket.on('typing', handleTyping);
    socket.on('messagesSeen', handleMessagesSeen);
    socket.on('messagesDeleted', handleMessagesDeleted);
    socket.on('newNotification', handleNewNotification);

    return () => {
      socket.off('receiveMessage', handleReceiveMessage);
      socket.off('userStatusUpdate', handleUserStatusUpdate);
      socket.off('typing', handleTyping);
      socket.off('messagesSeen', handleMessagesSeen);
      socket.off('messagesDeleted', handleMessagesDeleted);
      socket.off('newNotification', handleNewNotification);
    };
  }, [socket, selectedChatUser, user?.id, activeClassId, loadDashboard, userPage, fetchFeePaymentRequests, openFeeRequestModal]);

  useEffect(() => {
    const container = chatMessagesRef.current;
    if (!container) return;

    // Auto-scroll logic: only scroll if user is already near the bottom
    const isNearBottom = container.scrollHeight - container.scrollTop <= container.clientHeight + 150;
    if (isNearBottom || (adminChatMessages.length > 0 && adminChatMessages[adminChatMessages.length - 1].sender_id === user.id)) {
      container.scrollTop = container.scrollHeight;
    }
  }, [adminChatMessages, showAdminChatModal, user.id]);

  // Emit seen status when admin opens a chat or receives a message while chat is open
  useEffect(() => {
    if (showAdminChatModal && selectedChatUser && adminChatMessages.length > 0) {
      const unreadIds = adminChatMessages
        .filter(m => Number(m.sender_id) === Number(selectedChatUser.id) && m.status !== 'seen')
        .map(m => m.id);

      if (unreadIds.length > 0) {
        socket.emit("markSeen", {
          senderId: selectedChatUser.id,
          receiverId: user.id,
          messageIds: unreadIds
        });
      }
    }
  }, [showAdminChatModal, selectedChatUser, adminChatMessages, user?.id, socket]);

  const handleClassFilterChange = async (event) => {
    const value = event.target.value;
    setActiveClassId(value);
    loadDashboard(value, 1, userSearch, true);
  };

  const handlePageChange = (newPage) => {
    setUserPage(newPage);
    loadDashboard(activeClassId, newPage, userSearch, true);
    // Smooth scroll to the top of the user table
    const tableSection = document.querySelector('.user-management-card');
    if (tableSection) {
      tableSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  };

  const handleImageChange = async (event) => {
    const file = event.target.files?.[0];
    if (!file) return;

    try {
      const preparedFile = await prepareUploadFile(file, { maxBytes: 2 * 1024 * 1024, maxSizeMB: 1 });
      setImagePreview(URL.createObjectURL(preparedFile));
      setFormData((prev) => ({ ...prev, profile_image: preparedFile }));
    } catch (error) {
      toast.error(error.message || 'Image size must be less than 2MB');
      event.target.value = '';
    }
  };

  const handleEdit = (selectedUser) => {
    setEditingUser(selectedUser);
    setFormData({
      name: selectedUser.name || '',
      email: selectedUser.email || '',
      password: '',
      role: selectedUser.role || 'student',
      class_id: selectedUser.class_id || '',
      bio: selectedUser.bio || '',
      profile_image: null,
    });
    setImagePreview(resolveMediaUrl(selectedUser.profile_image) || null);
    setShowUserForm(true);
  };

  const handleUserSubmit = async (event) => {
    event.preventDefault();
    setSavingUser(true);
    try {
      const data = new FormData();
      Object.keys(formData).forEach(key => {
        if (key === 'profile_image' && formData[key] instanceof File) {
          data.append('profile_image', formData[key]);
        } else if (key !== 'profile_image') {
          data.append(key, formData[key] || '');
        }
      });

      if (editingUser) {
        await API.put(`/admin/users/${editingUser.id}`, data, {
          headers: { 'Content-Type': 'multipart/form-data' }
        });
        toast.success('User updated successfully');
      } else {
        await API.post('/admin/users', data, {
          headers: { 'Content-Type': 'multipart/form-data' }
        });
        toast.success(`${formData.role === 'teacher' ? 'Teacher' : 'Student'} created successfully`);
      }

      setShowUserForm(false);
      setEditingUser(null);
      setFormData(emptyForm);
      setImagePreview(null);
      await loadDashboard(activeClassId, userPage);
    } catch (error) {
      toast.error(error.response?.data?.message || 'Failed to save user');
    } finally {
      setSavingUser(false);
    }
  };

  const handleDeleteUser = async (id) => {
    if (!window.confirm('Delete this user?')) return;
    try {
      await API.delete(`/admin/users/${id}`);
      toast.success('User deleted');
      await loadDashboard(activeClassId, userPage);
    } catch (error) {
      toast.error(error.response?.data?.message || 'Delete failed');
    }
  };

  const handleClassSubmit = async (event) => {
    event.preventDefault();
    setSavingClass(true);
    try {
      await API.post('/classes', classFormData);
      toast.success(`Class ${classFormData.grade_level}${String(classFormData.section).toUpperCase()} created`);
      setClassFormData({ grade_level: '', section: '' });
      setShowClassForm(false);
      await loadDashboard(activeClassId, 1);
    } catch (error) {
      toast.error(error.response?.data?.message || 'Failed to create class');
    } finally {
      setSavingClass(false);
    }
  };

  const handleDeleteAnnouncement = async (id) => {
    if (!window.confirm('Delete this announcement?')) return;
    try {
      await API.delete(`/announcements/${id}`);
      toast.success('Announcement deleted');
      await loadDashboard(activeClassId, userPage);
    } catch (error) {
      toast.error(error.response?.data?.message || 'Failed to delete announcement');
    }
  };

  const handleNotificationClick = async (notif) => {
    setShowNotifications(false);
    
    // Persist read status in backend immediately so refresh doesn't bring it back
    const notifId = Number(notif.id);
    if (notifId && !isNaN(notifId)) {
      try {
        await API.put(`/admin/notifications/${notifId}/read`);
      } catch (err) {
        console.error("Failed to mark notification as read:", err);
      }
    }

    setNotifications(prev => prev.map(n => Number(n.id) === notifId ? { ...n, is_read: true } : n));
    
    if (notif.type === 'fee_payment_request') {
      const requestId = extractTaggedId(notif.message, 'requestId');
      await openFeeRequestModal(requestId);
      return;
    }

    if (notif.type === 'chat') {
      let targetUser = users.find(u => Number(u.id) === Number(notif.related_user_id));

      // If user isn't in current paginated view, fetch their specific details
      if (!targetUser) {
        try {
          const res = await API.get(`/admin/users/${notif.related_user_id}`);
          targetUser = res.data.user;
        } catch (err) {
          console.error("Failed to fetch user for chat from notification:", err);
        }
      }

      if (targetUser) openAdminChat(targetUser);
      return;
    }

    if (['salary_approved', 'salary_rejected'].includes(notif.type)) {
      const teacherId = Number(notif.related_user_id);
      if (teacherId) {
        navigate(`/admin/teacher/${teacherId}`);
      }
    }
  };

  const openAdminChat = useCallback(async (chatUser, before = null) => {
    const incomingUser = { ...chatUser };
    setSelectedChatUser(incomingUser);
    
    if (!before) {
      setAdminChatMessages([]);
      setLoadingChat(true);
      setShowAdminChatModal(true);
    }

    // Clear unread count for this user
    setUnreadMessages(prev => ({
      ...prev,
      [incomingUser.id]: 0
    }));

    // 1. Instant load from Chat Cache
    const cacheKey = CACHE_KEYS.CHAT_HISTORY(incomingUser.id);
    const cachedChat = getCache(cacheKey);
    if (Array.isArray(cachedChat)) {
      setAdminChatMessages(cachedChat);
      setShowAdminChatModal(true);
      // If cache is fresh (< 1 min), we might skip the background fetch
    }
    
    try {
      const params = before ? { before, limit: 25 } : { limit: 25 };
      const res = await API.get(`/admin/chat/${incomingUser.id}`, { params });
      const history = res.data.messages || [];
      setChatHasMore(res.data.hasMore);
      setChatCursor(res.data.pagination?.nextCursor || null);

      setAdminChatMessages(prev => {
        if (before) {
          // Prepend historical messages
          const filteredHistory = history.filter(hm => !prev.some(pm => pm.id === hm.id));
          return [...filteredHistory, ...prev];
        }
        // Initial load
        const newMessages = prev.filter(pm => !history.some(hm => hm.id === pm.id));
        const combined = [...history, ...newMessages].sort((a, b) => new Date(a.created_at) - new Date(b.created_at));
        
        // 2. Update Chat Cache
        if (!before) setCache(cacheKey, combined, 60); // Cache for 60 minutes (1 hour)
        return combined;
      });
    } catch (error) {
      toast.error(error.response?.data?.message || 'Failed to load chat');
    } finally {
      setLoadingChat(false);
    }
  }, [user.id]);

  const startVoiceRecording = async () => {
    try {
      if (isRecording) return;
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      recordedChunksRef.current = [];
      const preferredMimeType = ['audio/webm;codecs=opus', 'audio/webm', 'audio/ogg;codecs=opus']
        .find((item) => window.MediaRecorder?.isTypeSupported?.(item));
      const recorder = new MediaRecorder(stream, preferredMimeType ? { mimeType: preferredMimeType, audioBitsPerSecond: 64000 } : undefined);
      mediaRecorderRef.current = recorder;

      recorder.ondataavailable = (event) => {
        if (event.data && event.data.size > 0) recordedChunksRef.current.push(event.data);
      };

      recorder.onstop = () => {
        try {
          stream.getTracks().forEach((t) => t.stop());
        } catch { /* ignore */ }
        const blob = new Blob(recordedChunksRef.current, { type: recorder.mimeType || 'audio/webm' });
        const file = new File([blob], `voice-${Date.now()}.webm`, { type: blob.type });
        setAdminSelectedFile(file);
      };

      recorder.start();
      setIsRecording(true);
    } catch (e) {
      console.error(e);
      toast.error('Microphone permission denied or not available');
    }
  };

  const stopVoiceRecording = () => {
    try {
      const recorder = mediaRecorderRef.current;
      if (recorder && recorder.state !== 'inactive') recorder.stop();
    } catch (e) { console.error(e); }
    finally { setIsRecording(false); }
  };

  const handleChatScroll = useCallback((e) => {
    const { scrollTop } = e.currentTarget;
    if (scrollTop === 0 && chatHasMore && !loadingChat && selectedChatUser && chatCursor) {
      openAdminChat(selectedChatUser, chatCursor);
    }
  }, [chatHasMore, loadingChat, selectedChatUser, chatCursor, openAdminChat]);

  const closeAdminChat = () => {
    setShowAdminChatModal(false);
    setSelectedChatUser(null);
    setAdminChatMessages([]);
    setAdminNewMessage('');
    setAdminSelectedFile(null);
    setSelectedMessages([]);
    setSelectionMode(false);
  };

  const handleAdminFileSelect = async (event) => {
    const file = event.target.files?.[0];
    if (!file) return;

    try {
      const preparedFile = await prepareUploadFile(file, { maxBytes: 10 * 1024 * 1024, maxSizeMB: 2 });
      setAdminSelectedFile(preparedFile);
    } catch (error) {
      toast.error(error.message || 'File must be less than 10MB');
      event.target.value = '';
    }
  };

  const sendAdminMessage = async (event) => {
    event.preventDefault();
    if ((!adminNewMessage.trim() && !adminSelectedFile) || !selectedChatUser) {
      toast.warning('Please type a message or attach a file');
      return;
    }

    const payload = new FormData();
    payload.append('message', adminNewMessage.trim());
    if (adminSelectedFile) payload.append('file', adminSelectedFile);
    const optimisticMessage = createOptimisticMessage({
      senderId: user.id,
      receiverId: selectedChatUser.id,
      message: adminNewMessage,
      file: adminSelectedFile,
    });

    try {
      setSendingAdminMessage(true);
      setAdminChatMessages((prev) => [...prev, optimisticMessage]);
      setAdminNewMessage('');
      setAdminSelectedFile(null);
      if (adminFileInputRef.current) adminFileInputRef.current.value = '';
      const { data } = await API.post(`/admin/chat/${selectedChatUser.id}`, payload, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });
      setAdminChatMessages((prev) => prev.map((message) => message.id === optimisticMessage.id ? data.chat : message));
      // Delay revocation to prevent the "disappearing image" effect during URL swap
      setTimeout(() => releaseOptimisticMedia(optimisticMessage), 2000);
      if (socket) socket.emit('broadcastMessage', data.chat);
    } catch (error) {
      releaseOptimisticMedia(optimisticMessage);
      setAdminChatMessages((prev) => prev.filter((message) => message.id !== optimisticMessage.id));
      toast.error(error.response?.data?.message || 'Failed to send message');
    } finally {
      setSendingAdminMessage(false);
    }
  };

  const toggleMessageSelection = (id) => {
    setSelectedMessages((prev) => {
      const isSelected = prev.includes(id);
      let newSelection;
      if (isSelected) {
        newSelection = prev.filter((mid) => mid !== id);
      } else {
        newSelection = [...prev, id];
      }
      setSelectionMode(newSelection.length > 0);
      return newSelection;
    });
  };

  const selectAllMessages = () => {
    if (selectedMessages.length === adminChatMessages.length) {
      setSelectedMessages([]);
      setSelectionMode(false);
    } else {
      setSelectedMessages(adminChatMessages.map((m) => m.id));
      setSelectionMode(true);
    }
  };

  const openDeleteModal = (ids) => {
    const allSentByAdmin = ids.every(id => {
      const msg = adminChatMessages.find(m => m.id === id);
      return msg && msg.sender_id === user.id;
    });
    setDeleteModal({ show: true, ids, canDeleteEveryone: allSentByAdmin });
  };

  const handleDeleteConfirmed = async (type) => {
    try {
      const { ids } = deleteModal;
      await API.post(`/admin/chat/bulk-delete`, { messageIds: ids, type });
      
      if (type === 'everyone') {
        if (socket) socket.emit("deleteMessages", { receiverId: selectedChatUser.id, messageIds: ids });
        setAdminChatMessages(prev => prev.map(msg => 
          ids.includes(msg.id) ? { 
            ...msg, 
            message: "🚫 You deleted this message", 
            file_url: null, 
            deleted: true,
            status: 'deleted' 
          } : msg
        ));
      } else {
        setAdminChatMessages(prev => prev.filter(msg => !ids.includes(msg.id)));
      }

      setSelectedMessages([]);
      setSelectionMode(false);
      setDeleteModal({ show: false, ids: [], canDeleteEveryone: false });
      toast.success(type === 'everyone' ? "Deleted for everyone" : "Deleted for me");
    } catch (err) {
      toast.error("Failed to delete messages");
    }
  };

  const saveFile = async (url, originalName) => {
    try {
      const fullUrl = resolveMediaUrl(url);
      if (!fullUrl) throw new Error('Invalid file URL');
      
      const response = await fetch(fullUrl, { mode: 'cors' });
      if (!response.ok) throw new Error('Network error');

      const blob = await response.blob();
      const blobUrl = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = blobUrl;
      const fileName = originalName || fullUrl.split('/').pop().split('?')[0];
      link.setAttribute('download', `EduFlow_${fileName}`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(blobUrl);
    } catch (err) {
      const link = document.createElement('a');
      link.href = resolveMediaUrl(url);
      link.setAttribute('target', '_blank');
      link.setAttribute('download', originalName || 'download');
      link.click();
    }
  };

  const reviewFeePaymentRequest = async (status) => {
    const requestId = feeRequestModal.request?.id;
    if (!requestId) return;
    try {
      setFeeRequestModal((p) => ({ ...p, saving: true }));
      await API.put(`/fees/payment-requests/${requestId}`, {
        status,
        remarks: feeRequestModal.remarks,
        mark_fee_paid: status === 'approved',
      });
      toast.success(status === 'approved' ? 'Approved' : 'Rejected');
      setFeeRequestModal({ open: false, request: null, remarks: '', saving: false });
      await fetchFeePaymentRequests();
      await fetchAdminNotifications();
      await loadDashboard(activeClassId, userPage, userSearch);
    } catch (e) {
      toast.error(e.response?.data?.message || 'Failed to update request');
      setFeeRequestModal((p) => ({ ...p, saving: false }));
    }
  };

  const handleBroadcast = async (event) => {
    event.preventDefault();
    if (!broadcastData.class_id || !broadcastData.message.trim()) {
      toast.warning('Select a class section and write a message first');
      return;
    }

    try {
      setSendingBroadcast(true);
      await API.post('/admin/chat/broadcast', {
        class_id: broadcastData.class_id,
        message: broadcastData.message.trim(),
      });
      toast.success('Broadcast sent successfully');
      setBroadcastData((prev) => ({ ...prev, message: '' }));
      await loadDashboard(activeClassId);
    } catch (error) {
      toast.error(error.response?.data?.message || 'Failed to send broadcast');
    } finally {
      setSendingBroadcast(false);
    }
  };

  const normalizeLogoUrl = (path) => {
    return resolveMediaUrl(path);
  };

  const currentLogo = normalizeLogoUrl(dashboard?.school?.logo_url) || logo;

  const handleExportReport = () => {
    if (!dashboard) {
      toast.warning('Dashboard data is still loading');
      return;
    }

    try {
      openAdminReportPrintWindow({
        analytics: dashboard,
        template: {
          ...reportTemplate,
          schoolName: reportTemplate.schoolName?.trim() || dashboard?.school?.name || 'EduFlow',
        },
        logoUrl: currentLogo,
      });
    } catch (error) {
      toast.error(error.message || 'Failed to open print preview');
    }
  };

  const feeCollectionChart = (dashboard?.feeByClass || []).map((row) => ({
    name: row.class_name,
    collected: Number(row.paid_fees || 0),
    pending: Number(row.pending_fees || 0),
  }));

  const resultsChart = (dashboard?.resultsByClass || []).map((row) => ({
    name: row.class_name,
    average: Number(row.average_marks || 0),
  }));

  const attendanceChart = (dashboard?.attendanceByClass || []).map((row) => ({
    name: row.class_name,
    percentage: Number(row.attendance_percentage || 0),
  }));

  const announcementHighlights = dashboard?.recentAnnouncements || [];

  if (loading) {
    return (
      <div className="loader-container">
        <div className="minimalist-spinner"></div>
        <p>Loading Admin Dashboard...</p>
      </div>
    );
  }

  if (!dashboard) {
    return (
      <div className="loader-container">
        <div className="minimalist-spinner"></div>
        <p>Refreshing dashboard data...</p>
      </div>
    );
  }

  return (
    <div className="admin-shell">
      <nav className="admin-navbar">
        <div className="admin-navbar-content">
          <div className="brand-block">
            <img
              src={currentLogo}
              alt="School logo"
              className="admin-brand-logo"
              crossOrigin="anonymous"
              onError={(e) => {
                e.currentTarget.onerror = null;
                e.currentTarget.src = logo;
              }}
            />
            <div>
              <p className="eyebrow">{dashboard?.school?.subscription_status === 'active' ? 'Active School Tenant' : 'School Management System'}</p>
              <h1 className="admin-title">{dashboard?.school?.name || 'EDU FLOW'}</h1>
              <p className="admin-subtitle">
                {dashboard?.school?.logo_url ? 'Branded tenant dashboard' : 'Live operations, communication, reporting, and academic analytics.'}
              </p>
              {dashboard?.school && (
                <div className="subscription-meta">
                  <span className={`subscription-pill ${dashboard.school.subscription_status || 'inactive'}`}>
                    {dashboard.school.subscription_status?.toUpperCase() || 'INACTIVE'}
                  </span>
                  {dashboard.school.subscription_expires_at && (
                    <small>Expires {new Date(dashboard.school.subscription_expires_at).toLocaleDateString()}</small>
                  )}
                </div>
              )}
            </div>
          </div>

          <div className="admin-user-info">
            <div>
              <p className="admin-username">{user?.name}</p>
              <p className="admin-role">Administrator</p>
            </div>
            <button onClick={logout} className="logout-btn">
              <FaSignOutAlt />
            </button>
            <div className="notification-bell" onClick={() => setShowNotifications(!showNotifications)}>
              <FaBell />
              {unreadCount > 0 && <span className="notification-dot">{unreadCount}</span>}
            </div>
          </div>
        </div>
      </nav>

      {showNotifications && (
        <div className="notification-dropdown admin-notif">
          <div className="notification-dropdown-head">
            <div>
              <h4>System Notifications</h4>
              <p>Tap an item to open the related action.</p>
            </div>
            <div className="notification-head-actions">
              <span className="notification-summary">{unreadCount} unread</span>
              <button type="button" className="close-btn notif-close-btn" onClick={() => setShowNotifications(false)} aria-label="Close notifications">
                <FaTimes />
              </button>
            </div>
          </div>
          {notifications.length === 0 ? (
            <p className="no-notif">No new alerts</p>
          ) : (
            notifications.map(notif => (
              <div key={notif.id} className={`notification-item ${!notif.is_read ? 'unread' : ''}`} onClick={() => handleNotificationClick(notif)}>
                <strong>{notif.title}</strong>
                <p>{stripNotificationTags(notif.message || 'Sent a file')}</p>
                <small>{new Date(notif.created_at).toLocaleTimeString()}</small>
              </div>
            ))
          )}
        </div>
      )}

      <main className="admin-main">
        <section className="hero-panel">
          <div className="hero-copy" style={{ flex: '1 1 500px' }}>
            <span className="hero-chip"><FaChartBar /> Real-time Snapshot</span>
            <h2>Monitor school performance, message class sections, and export branded reports from one dashboard.</h2>
            <p>
              Current scope: <strong>{selectedClassLabel}</strong>. Data refreshes every 30 seconds and online status updates instantly through sockets.
            </p>
          </div>

          <div className="hero-actions" style={{ flex: '1 1 300px', display: 'flex', flexWrap: 'wrap', gap: '10px' }}>
            <label className="field-label">
              Filter by class section
              <select value={activeClassId} onChange={handleClassFilterChange} className="form-input">
                <option value="">All classes</option>
                {classes.map((item) => (
                  <option key={item.id} value={item.id}>
                    {item.name} {item.teacher_name ? `- ${item.teacher_name}` : ''}
                  </option>
                ))}
              </select>
            </label>
            <button className="btn-secondary" onClick={() => loadDashboard(activeClassId)}>
              <FaUsers /> Refresh Data
            </button>
            <button className="btn-secondary" onClick={() => setSubscriptionRequestModal((prev) => ({ ...prev, open: true }))}>
              <FaMoneyBillWave /> Request Subscription
            </button>
            <button className="btn-primary" onClick={handleExportReport}>
              <FaDownload /> Export PDF
            </button>
          </div>
        </section>

        <section className="stats-grid">
          <StatCard title="Total Students" value={summary.totalStudents} icon={FaUserGraduate} color="blue" subtitle="Active student records" />
          <StatCard title="Total Teachers" value={summary.totalTeachers} icon={FaChalkboardTeacher} color="green" subtitle="Teaching workforce" />
          <div className="clickable-card" onClick={() => setShowClassForm(true)}>
            <StatCard title="Class Sections" value={summary.totalClasses} icon={FaSchool} color="purple" subtitle="Tap to create a new section" />
          </div>
          <StatCard title="Announcements" value={summary.totalAnnouncements} icon={FaBullhorn} color="orange" subtitle="Published notices" />
          <div className="clickable-card" onClick={() => setFeeRequestModal((p) => ({ ...p, open: true, request: feePaymentRequests[0] || null }))}>
            <StatCard
              title="Fee Requests"
              value={feePaymentRequests.length}
              icon={FaDownload}
              color="pink"
              subtitle="Pending manual payments"
            />
          </div>
          <div className="clickable-card" onClick={() => setSubscriptionRequestModal((p) => ({ ...p, open: true }))}>
            <StatCard
              title="Subscription"
              value={dashboard?.school?.subscription_status ? dashboard.school.subscription_status.toUpperCase() : 'NONE'}
              icon={FaMoneyBillWave}
              color="teal"
              subtitle={dashboard?.school?.subscription_expires_at ? `Expires ${new Date(dashboard.school.subscription_expires_at).toLocaleDateString()}` : 'Request access from Super Admin'}
            />
          </div>
        </section>

        <section className="analytics-grid">
          <article className="admin-card chart-card">
            <div className="section-head">
              <div>
                <h3>Attendance Percentage</h3>
                <p>Class-wise attendance based on live attendance entries.</p>
              </div>
            </div>
            <div className="chart-wrap">
              <ResponsiveContainer width="100%" height={280}>
                <BarChart data={attendanceChart}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} />
                  <XAxis dataKey="name" />
                  <YAxis domain={[0, 100]} />
                  <Tooltip formatter={(value) => `${value}%`} />
                  <Bar dataKey="percentage" radius={[12, 12, 0, 0]} fill="#2563eb" />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </article>

          <article className="admin-card chart-card">
            <div className="section-head">
              <div>
                <h3>Overall Result Trend</h3>
                <p>Average marks grouped by class section.</p>
              </div>
            </div>
            <div className="chart-wrap">
              <ResponsiveContainer width="100%" height={280}>
                <LineChart data={resultsChart}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} />
                  <XAxis dataKey="name" />
                  <YAxis domain={[0, 100]} />
                  <Tooltip formatter={(value) => `${value}%`} />
                  <Line type="monotone" dataKey="average" stroke="#0f766e" strokeWidth={3} dot={{ r: 4 }} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </article>

          <article className="admin-card chart-card">
            <div className="section-head">
              <div>
                <h3>Fee Analytics</h3>
                <p>Collection vs pending fee balance by class section.</p>
              </div>
            </div>
            <div className="chart-wrap">
              <ResponsiveContainer width="100%" height={280}>
                <BarChart data={feeCollectionChart}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} />
                  <XAxis dataKey="name" />
                  <YAxis />
                  <Tooltip formatter={(value) => formatCurrency(value)} />
                  <Legend />
                  <Bar dataKey="collected" stackId="fees" fill="#10b981" radius={[10, 10, 0, 0]} />
                  <Bar dataKey="pending" stackId="fees" fill="#f97316" radius={[10, 10, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </article>

          <article className="admin-card chart-card">
            <div className="section-head">
              <div>
                <h3>Subject Performance</h3>
                <p>Average subject-wise academic outcome.</p>
              </div>
            </div>
            <div className="chart-wrap">
              <ResponsiveContainer width="100%" height={280}>
                <PieChart>
                  <Pie
                    data={dashboard?.subjectPerformance || []}
                    dataKey="average_marks"
                    nameKey="subject"
                    cx="50%"
                    cy="50%"
                    outerRadius={94}
                    label={({ subject, percent }) => `${subject} ${(percent * 100).toFixed(0)}%`}
                  >
                    {(dashboard?.subjectPerformance || []).map((entry, index) => (
                      <Cell key={entry.subject} fill={CHART_COLORS[index % CHART_COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip formatter={(value) => `${Number(value).toFixed(1)}%`} />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </article>
        </section>

        <section className="admin-insight-grid">
          <article className="admin-card">
            <div className="section-head">
              <div>
                <h3><FaBroadcastTower /> Class Broadcast</h3>
                <p>Send an announcement-style message to a selected class section instantly.</p>
              </div>
            </div>
            <form onSubmit={handleBroadcast} className="stack-form">
              <select
                value={broadcastData.class_id}
                onChange={(event) => setBroadcastData((prev) => ({ ...prev, class_id: event.target.value }))}
                className="form-input"
                required
              >
                <option value="">Select class section</option>
                {classes.map((item) => (
                  <option key={item.id} value={item.id}>
                    {item.name} {item.teacher_name ? `- ${item.teacher_name}` : ''}
                  </option>
                ))}
              </select>
              <textarea
                className="form-textarea"
                placeholder="Type a live message for the selected class section..."
                value={broadcastData.message}
                onChange={(event) => setBroadcastData((prev) => ({ ...prev, message: event.target.value }))}
                required
              />
              <button type="submit" className="btn-primary wide-btn" disabled={sendingBroadcast}>
                <FaPaperPlane /> {sendingBroadcast ? 'Sending...' : 'Send Broadcast'}
              </button>
            </form>
          </article>

          <article className="admin-card">
            <div className="section-head">
              <div>
                <h3><FaDownload /> PDF Template</h3>
                <p>Customize the printable report template with school branding and leadership details.</p>
              </div>
            </div>
            <div className="template-grid">
              <input
                className="form-input"
                placeholder="School name"
                value={reportTemplate.schoolName}
                onChange={(event) => setReportTemplate((prev) => ({ ...prev, schoolName: event.target.value }))}
              />
              <input
                className="form-input"
                placeholder="Report title"
                value={reportTemplate.reportTitle}
                onChange={(event) => setReportTemplate((prev) => ({ ...prev, reportTitle: event.target.value }))}
              />
              <input
                className="form-input"
                placeholder="Principal name"
                value={reportTemplate.principalName}
                onChange={(event) => setReportTemplate((prev) => ({ ...prev, principalName: event.target.value }))}
              />
              <input
                className="form-input"
                placeholder="Prepared by"
                value={reportTemplate.preparedBy}
                onChange={(event) => setReportTemplate((prev) => ({ ...prev, preparedBy: event.target.value }))}
              />
              <input
                className="form-input"
                type="color"
                value={reportTemplate.accentColor}
                onChange={(event) => setReportTemplate((prev) => ({ ...prev, accentColor: event.target.value }))}
              />
              <textarea
                className="form-textarea compact-textarea"
                placeholder="Footer note"
                value={reportTemplate.footerNote}
                onChange={(event) => setReportTemplate((prev) => ({ ...prev, footerNote: event.target.value }))}
              />
            </div>
          </article>
        </section>

        <section className="admin-insight-grid">
          <article className="admin-card">
            <div className="section-head">
              <div>
                <h3><FaSchool /> Class Overview</h3>
                <p>See teacher allocation, section size, and attendance quality in one place.</p>
              </div>
            </div>
            <div className="mini-table">
              <div className="mini-table-head">
                <span>Class</span>
                <span>Teacher</span>
                <span>Students</span>
                <span>Attendance</span>
              </div>
              {classes.map((item) => {
                const attendance = dashboard?.attendanceByClass?.find((row) => row.class_id === item.id);
                return (
                  <div 
                    className="mini-table-row" 
                    key={item.id} 
                    onClick={() => { setActiveClassId(item.id); loadDashboard(item.id); }}
                  >
                    <span>{item.name}</span>
                    <span>{item.teacher_name || 'Unassigned'}</span>
                    <span>{item.student_count}</span>
                    <span>{attendance ? `${Number(attendance.attendance_percentage || 0).toFixed(1)}%` : 'N/A'}</span>
                  </div>
                );
              })}
            </div>
          </article>

          <article className="admin-card">
            <div className="section-head">
              <div>
                <h3><FaBell /> Recent Updates</h3>
                <p>Latest announcements and attendance trend snapshots for quick review.</p>
              </div>
            </div>
            <div className="feed-list">
              {announcementHighlights.map((item) => (
                <div className="feed-item" key={item.id}>
                  <strong>{item.title}</strong>
                  <p>{item.description}</p>
                  <span>{new Date(item.date).toLocaleDateString()}</span>
                </div>
              ))}
              {!announcementHighlights.length ? <p className="muted-copy">No recent updates available.</p> : null}
            </div>
            <div className="trend-panel">
              <ResponsiveContainer width="100%" height={180}>
                <LineChart data={dashboard?.attendanceTrend || []}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} />
                  <XAxis dataKey="day" />
                  <YAxis domain={[0, 100]} />
                  <Tooltip formatter={(value) => `${value}%`} />
                  <Line type="monotone" dataKey="attendance_percentage" stroke="#7c3aed" strokeWidth={3} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </article>
        </section>

        <section className="teachers-overview-section">
          <div className="section-head">
            <div className="flex items-center gap-3">
              <div className="section-icon-wrap"><FaChalkboardTeacher /></div>
              <div>
                <h3>Teachers Directory</h3>
                <p>Manage performance and payroll for your teaching staff.</p>
              </div>
            </div>
          </div>
          <div className="teacher-grid">
            {teachers.length > 0 ? (
              teachers.map((t) => (
                <div key={t.id} className="teacher-card">
                  <div className="t-card-main">
                    {t.profile_image ? (
                      <img src={t.profile_image} alt={t.name} className="t-img" />
                    ) : (
                      <div className="t-avatar-fallback">{t.name[0]}</div>
                    )}
                    <div className="t-meta">
                      <h4>{t.name}</h4>
                      <span className="t-tag">{t.class_name || 'Unassigned'}</span>
                      <p className={`t-status ${t.online ? 'is-online' : ''}`}>{t.online ? 'Online' : 'Offline'}</p>
                    </div>
                  </div>
                  <button className="btn-details-link" onClick={() => navigate(`/admin/teacher/${t.id}`)}>
                    <FaAddressCard /> View Full Profile & Salary
                  </button>
                </div>
              ))
            ) : <p className="empty-msg">No teachers found in current filter.</p>}
          </div>
        </section>

        <div className="user-management-card">
          <div className="user-table-filters">
            <div className="search-box" >
            
              <input className='search-input'
              style={{ width: '100%' , maxWidth: '400px', padding: '8px 12px', borderRadius: '4px', border: '1px solid #ccc', }}
                type="text"
                placeholder="Search by name or id..."
                value={userSearch}
                onChange={(e) => setUserSearch(e.target.value)}
              />
            </div>
            {isRefreshing && <div className="refresh-pill"><FaSpinner className="animate-spin" style={{marginRight: '6px'}} /> Updating...</div>}
          </div>
          <UserTable
            users={users}
            onEdit={handleEdit}
            onDelete={handleDeleteUser}
            onAddUser={() => {
              setEditingUser(null);
              setFormData(emptyForm);
              setImagePreview(null);
              setShowUserForm(true);
            }}
            unreadCounts={unreadMessages}
            onChat={openAdminChat}
            loading={loading}
          />
        </div>
        
        {totalUsers > userLimit && (
          <div className="pagination-bar">
            <button className="pagi-btn" disabled={userPage === 1} onClick={() => handlePageChange(userPage - 1)}>
              Previous
            </button>
            <span className="pagi-info">Page {userPage} of {Math.ceil(totalUsers / userLimit)}</span>
            <button className="pagi-btn" disabled={userPage >= Math.ceil(totalUsers / userLimit)} onClick={() => handlePageChange(userPage + 1)}>
              Next
            </button>
          </div>
        )}

        <section className="announcements-section">
          <h2 className="section-title"><FaBullhorn /> Announcements</h2>
          <AnnouncementForm onSuccess={() => loadDashboard(activeClassId, userPage)} />
          <AnnouncementList announcements={announcements} onDelete={handleDeleteAnnouncement} canDelete />
        </section>
      </main>

      {showUserForm && (
        <div className="modal">
          <div className="modal-content">
            <div className="modal-body">
              <h2 className="modal-title">{editingUser ? 'Edit User' : 'Add New User'}</h2>
              <form onSubmit={handleUserSubmit} className="user-form">
                <div className="image-upload-area">
                  <div className="preview-container">
                    {imagePreview ? <img src={imagePreview} alt="Preview" className="preview-image" /> : <div className="no-image">No Image</div>}
                  </div>
                  <label className="upload-label">
                    Choose Profile Image
                    <input type="file" accept="image/*" onChange={handleImageChange} className="hidden-file" />
                  </label>
                </div>

                <input
                  className="form-input"
                  placeholder="Full Name"
                  value={formData.name}
                  onChange={(event) => setFormData((prev) => ({ ...prev, name: event.target.value }))}
                  required
                />
                <input
                  type="email"
                  className="form-input"
                  placeholder="Email"
                  value={formData.email}
                  onChange={(event) => setFormData((prev) => ({ ...prev, email: event.target.value }))}
                  required
                />
                {!editingUser ? (
                  <input
                    type="password"
                    className="form-input"
                    placeholder="Password"
                    value={formData.password}
                    onChange={(event) => setFormData((prev) => ({ ...prev, password: event.target.value }))}
                    required
                  />
                ) : null}
                <select
                  className="form-input"
                  value={formData.role}
                  onChange={(event) => setFormData((prev) => ({ ...prev, role: event.target.value }))}
                >
                  <option value="student">Student</option>
                  <option value="teacher">Teacher</option>
                </select>
                <select
                  className="form-input"
                  value={formData.class_id}
                  onChange={(event) => setFormData((prev) => ({ ...prev, class_id: event.target.value }))}
                >
                  <option value="">Select Class Section</option>
                  {classes.map((item) => (
                    <option key={item.id} value={item.id}>{item.name}</option>
                  ))}
                </select>
                <textarea
                  className="form-textarea"
                  placeholder="Bio"
                  value={formData.bio}
                  onChange={(event) => setFormData((prev) => ({ ...prev, bio: event.target.value }))}
                />

                <div className="form-actions">
                  <button type="button" className="btn-cancel" onClick={() => setShowUserForm(false)}>Cancel</button>
                  <button type="submit" className="btn-primary" disabled={savingUser}>{savingUser ? (editingUser ? 'Updating...' : 'Creating...') : (editingUser ? 'Update User' : 'Create User')}</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}

      {showClassForm && (
        <div className="modal">
          <div className="modal-content small">
            <div className="modal-body">
              <h2 className="modal-title">Create New Class Section</h2>
              <form onSubmit={handleClassSubmit} className="user-form">
                <input
                  type="number"
                  className="form-input"
                  placeholder="Grade Level"
                  value={classFormData.grade_level}
                  onChange={(event) => setClassFormData((prev) => ({ ...prev, grade_level: event.target.value }))}
                  required
                />
                <input
                  className="form-input"
                  placeholder="Section"
                  maxLength="2"
                  value={classFormData.section}
                  onChange={(event) => setClassFormData((prev) => ({ ...prev, section: event.target.value }))}
                  required
                />
                <div className="form-actions">
                  <button type="button" className="btn-cancel" onClick={() => setShowClassForm(false)}>Cancel</button>
                  <button type="submit" className="btn-primary" disabled={savingClass}><FaPlus /> {savingClass ? 'Creating...' : 'Create Section'}</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}

      <ChatModal
        isOpen={showAdminChatModal}
        contact={selectedChatUser}
        currentUserId={user?.id}
        messages={adminChatMessages}
        loading={loadingChat}
        hasMore={chatHasMore}
        isTyping={isTyping}
        typingLabel={`${selectedChatUser?.name || 'User'} is typing...`}
        bannerText="Admin conversations support files, voice notes, and live seen status."
        emptyStateText="No messages yet. Start the conversation."
        onClose={closeAdminChat}
        onScroll={handleChatScroll}
        onQuickSelectLast={() => {
          const lastId = adminChatMessages[adminChatMessages.length - 1]?.id;
          if (!lastId) return;
          setSelectedMessages([lastId]);
          setSelectionMode(true);
        }}
        onSelectAll={selectAllMessages}
        onOpenDelete={() => openDeleteModal(selectedMessages)}
        selectedMessages={selectedMessages}
        selectionMode={selectionMode}
        onToggleMessageSelection={toggleMessageSelection}
        messageValue={adminNewMessage}
        onMessageChange={(event) => {
          setAdminNewMessage(event.target.value);
          if (selectedChatUser && socket) socket.emit("typing", { senderId: user.id, receiverId: selectedChatUser.id });
        }}
        onSend={sendAdminMessage}
        sendingMessage={sendingAdminMessage}
        selectedFile={adminSelectedFile}
        filePreview={null}
        onFileSelect={handleAdminFileSelect}
        onRemoveFile={() => setAdminSelectedFile(null)}
        fileInputRef={adminFileInputRef}
        attachAccept="image/*,application/pdf,video/*,audio/*"
        isRecording={isRecording}
        onToggleRecording={() => (isRecording ? stopVoiceRecording() : startVoiceRecording())}
        saveFile={saveFile}
        inputPlaceholder="Type a message..."
        statusText={selectedChatUser?.online ? 'Online' : `Last seen: ${formatDateTime(selectedChatUser?.last_seen)}`}
        metaText={selectedChatUser?.role ? selectedChatUser.role.charAt(0).toUpperCase() + selectedChatUser.role.slice(1) : 'Conversation'}
        avatarFallback={selectedChatUser?.role?.[0]?.toUpperCase() || 'U'}
      />

      {false && showAdminChatModal && selectedChatUser ? (
        <div className="modal chat-modal-overlay">
          <div className="chat-modal">
            <div className="chat-header">
              <div className="chat-user-info">
                <div className="chat-avatar">
                  {selectedChatUser.profile_image ? (
                    <img src={selectedChatUser.profile_image} alt="User" />
                  ) : (
                    <div className="avatar-placeholder">{selectedChatUser.role[0].toUpperCase()}</div>
                  )}
                </div>
                <div>
                  <h3 className="chat-user-name">{selectedChatUser.name}</h3>
                  <div className="status-info">
                    <span className={`status-dot ${selectedChatUser.online ? 'online' : 'offline'}`}></span>
                    <span>{selectedChatUser.online ? 'Online' : `Last seen: ${formatDateTime(selectedChatUser.last_seen)}`}</span>
                  </div>
                </div>
              </div>

              <div className="chat-header-actions">
                {selectedMessages.length > 0 ? (
                  <>
                    <span className="selection-count">{selectedMessages.length} selected</span>
                    <button className="header-action-btn" onClick={selectAllMessages} title="Select All">
                      <FaCheckSquare />
                    </button>
                    <button className="header-action-btn delete-action" onClick={() => openDeleteModal(selectedMessages)} title="Delete Selected">
                      <FaTrash />
                    </button>
                  </>
                ) : (
                  <button className="header-action-btn" onClick={() => {
                    const lastId = adminChatMessages[adminChatMessages.length - 1]?.id;
                    if (lastId) { setSelectedMessages([lastId]); setSelectionMode(true); }
                  }}>
                    <FaEllipsisV />
                  </button>
                )}
                <button onClick={closeAdminChat} className="close-btn" title="Close Chat">×</button>
              </div>
            </div>

            <div className="chat-messages" ref={chatMessagesRef} onScroll={handleChatScroll}>
              {loadingChat && <div className="text-center p-2 text-sm text-gray-500">Messages loading...</div>}
              {chatHasMore && !loadingChat && <div className="text-center p-1 text-xs text-blue-500">Scroll up to load more</div>}
              {adminChatMessages.map((message) => {
                const isSent = Number(message.sender_id) === Number(user?.id);
                const rawFileUrl = message.file_url;
                const fileUrl = rawFileUrl ? resolveMediaUrl(rawFileUrl) : null;                
                const mType = message.message_type || (rawFileUrl ? 'file' : 'text');

                return (
                  <div
                    key={message.id}
                    className={`message ${isSent ? 'sent' : 'received'}
                      ${selectedMessages.includes(message.id) ? 'selected' : ''}
                      ${selectionMode ? 'in-selection-mode' : ''} 
                      ${message.deleted ? 'deleted-msg' : ''}`}
                    onDoubleClick={() => !message.deleted && toggleMessageSelection(message.id)}
                    onClick={() => !message.deleted && selectionMode && toggleMessageSelection(message.id)}
                  >
                    {!message.deleted && fileUrl && (
                      <div className="file-message">
                        {mType === 'image' || isImage(rawFileUrl) ? (
                          <img
                            src={fileUrl}
                            alt={message.file_name || "Image"}
                            className="chat-image"
                            loading="lazy"
                            crossOrigin="anonymous"
                            onError={(e) => { e.target.src = 'https://via.placeholder.com/300?text=Error+Loading+Image'; }}
                            onClick={(e) => { e.stopPropagation(); setLightboxImage(fileUrl); }}
                          />
                        ) : mType === 'audio' || isAudio(rawFileUrl) ? (
                          <audio controls className="chat-audio">
                            <source src={fileUrl} />
                          </audio>
                        ) : rawFileUrl?.match(/\.pdf$/i) ? (
                          <a className="file-attachment" href={fileUrl} target="_blank" rel="noreferrer">
                            📄 {message.file_name || "PDF"}
                          </a>
                        ) : mType === 'video' || isVideo(rawFileUrl) ? (
                          <video controls className="chat-video">
                            <source src={fileUrl} />
                          </video>
                        ) : (                          
                          <div className="file-attachment">📎 {message.file_name || "File"}</div>
                        )}
                        <button 
                          onClick={(e) => { e.preventDefault(); e.stopPropagation(); saveFile(fileUrl, message.file_name); }}
                          className="download-btn"
                        >
                          <FaDownload /> Save
                        </button>
                      </div>
                    )}
                    {message.message && <p className="message-text">{message.message}</p>}
                    <div className="message-footer">
                      <small className="message-timestamp">{new Date(message.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</small>
                      {isSent && message.status === 'seen' && <FaCheckDouble className="seen-icon" />}
                    </div>
                  </div>
                );
              })}
              {isTyping && (
                <div className="typing-indicator">
                  <span>User is typing</span>
                  <span className="typing-dots"><span>.</span><span>.</span><span>.</span></span>
                </div>
              )}
            </div>

            <div className="chat-input-area">
              {adminSelectedFile && (
                <div className="selected-file-info">
                  <span>📎 {adminSelectedFile.name}</span>
                  <button onClick={() => setAdminSelectedFile(null)} className="remove-file-btn"><FaTimes /></button>
                </div>
              )}
              <div className="input-wrapper">
                <label className="attach-btn">
                  <FaPaperclip />
                  <input ref={adminFileInputRef} type="file" className="hidden-file" onChange={handleAdminFileSelect} accept="image/*,application/pdf,video/*,audio/*" />
                </label>

                <button
                  type="button"
                  className={`attach-btn ${isRecording ? 'recording' : ''}`}
                  onClick={() => (isRecording ? stopVoiceRecording() : startVoiceRecording())}
                  title={isRecording ? 'Stop recording' : 'Record voice message'}
                >
                  {isRecording ? <FaStopCircle /> : <FaMicrophone />}
                </button>

                <input
                  value={adminNewMessage}
                  onChange={(event) => {
                    setAdminNewMessage(event.target.value);
                    if (selectedChatUser && socket) socket.emit("typing", { senderId: user.id, receiverId: selectedChatUser.id });
                  }}
                  placeholder="Type a message..."
                  onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendAdminMessage(e); } }}
                />
                <button onClick={sendAdminMessage} className="send-btn text-send-btn" title="Send message" disabled={sendingAdminMessage}>
                  {sendingAdminMessage ? 'Sending...' : <FaPaperPlane />}
                </button>
              </div>
            </div>
          </div>
        </div>
      ) : null}

      {subscriptionRequestModal.open ? (
        <div className="modal-overlay">
          <div className="modal-content" style={{
            maxWidth: 720,
            borderRadius: '16px',
            boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
            border: 'none',
            background: 'white',
            scrollbarWidth: 'none',
            overflowY: 'auto',
            maxHeight: '90vh',
          }}>
            <div className="modal-header" style={{
              background: 'linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)',
              color: 'white',
              padding: '20px 24px',
              borderBottom: 'none'
            }}>
              <h3 style={{ margin: 0, fontSize: '24px', fontWeight: '600' }}>
                🔄 Request Subscription Renewal
              </h3>
              <button
                className="close-btn"
                onClick={() => setSubscriptionRequestModal({ open: false, duration: '1month', price: '', file: null, loading: false, screenshotPreview: null })}
                style={{
                  background: 'rgba(255,255,255,0.2)',
                  border: 'none',
                  borderRadius: '50%',
                  width: '32px',
                  height: '32px',
                  color: 'white',
                  fontSize: '18px',
                  cursor: 'pointer'
                }}
              >
                ×
              </button>
            </div>
            <div style={{ padding: '24px' }}>
              <div style={{
                background: '#f8fafc',
                padding: '16px',
                borderRadius: '12px',
                marginBottom: '20px',
                border: '1px solid #e2e8f0'
              }}>
                <div style={{ fontSize: '14px', color: '#64748b', marginBottom: '8px' }}>
                  📋 Subscription Renewal Process
                </div>
                <div style={{ fontSize: '13px', color: '#475569', lineHeight: '1.5' }}>
                  Submit your payment details and screenshot. Super Admin will review and approve your subscription renewal.
                  Your school will remain active during the approval process.
                </div>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '24px' }}>
                <div>
                  <label className="field-label" style={{ fontWeight: '600', color: '#374151' }}>
                    ⏰ Duration
                  </label>
                  <select
                    value={subscriptionRequestModal.duration}
                    onChange={(e) => setSubscriptionRequestModal((prev) => ({ ...prev, duration: e.target.value }))}
                    className="form-input"
                    style={{
                      width: '100%',
                      padding: '12px',
                      border: '1px solid #d1d5db',
                      borderRadius: '8px',
                      fontSize: '14px'
                    }}
                  >
                    <option value="15days">15 Days</option>
                    <option value="1month">1 Month</option>
                    <option value="3months">3 Months</option>
                    <option value="6months">6 Months</option>
                    <option value="1year">1 Year</option>
                  </select>
                </div>
                <div>
                  <label className="field-label" style={{ fontWeight: '600', color: '#374151' }}>
                    💰 Price (PKR)
                  </label>
                  <input
                    type="number"
                    value={subscriptionRequestModal.price}
                    onChange={(e) => setSubscriptionRequestModal((prev) => ({ ...prev, price: e.target.value }))}
                    className="form-input"
                    placeholder="Enter subscription cost"
                    min="0"
                    style={{
                      width: '100%',
                      padding: '12px',
                      border: '1px solid #d1d5db',
                      borderRadius: '8px',
                      fontSize: '14px'
                    }}
                  />
                </div>
              </div>

              <div style={{ marginBottom: '24px' }}>
                <label className="field-label" style={{ fontWeight: '600', color: '#374151' }}>
                  📸 Payment Screenshot *
                </label>
                <input
                  type="file"
                  accept="image/*"
                  onChange={handleSubscriptionFileChange}
                  style={{
                    width: '100%',
                    padding: '12px',
                    border: '2px dashed #cbd5e1',
                    borderRadius: '8px',
                    background: '#f8fafc',
                    cursor: 'pointer'
                  }}
                />
                <div style={{ fontSize: '12px', color: '#64748b', marginTop: '4px' }}>
                  Upload a clear screenshot of your payment confirmation (Max 5MB)
                </div>
                {subscriptionRequestModal.screenshotPreview && (
                  <div style={{
                    marginTop: '12px',
                    border: '1px solid #e2e8f0',
                    borderRadius: '12px',
                    overflow: 'hidden',
                    background: '#f8fafc'
                  }}>
                    <img
                      src={subscriptionRequestModal.screenshotPreview}
                      alt="Payment Preview"
                      style={{
                        width: '100%',
                        maxHeight: '300px',
                        objectFit: 'contain',
                        display: 'block'
                      }}
                    />
                  </div>
                )}
              </div>

              <div style={{
                display: 'flex',
                gap: '12px',
                justifyContent: 'flex-end',
                paddingTop: '20px',
                borderTop: '1px solid #e2e8f0'
              }}>
                <button
                  className="btn"
                  onClick={() => setSubscriptionRequestModal({ open: false, duration: '1month', price: '', file: null, loading: false, screenshotPreview: null })}
                  style={{
                    padding: '10px 20px',
                    border: '1px solid #d1d5db',
                    background: 'white',
                    borderRadius: '8px',
                    cursor: 'pointer',
                    fontWeight: '500'
                  }}
                >
                  Cancel
                </button>
                <button
                  className="btn btn-success"
                  disabled={subscriptionRequestModal.loading || !subscriptionRequestModal.price || !subscriptionRequestModal.file}
                  onClick={submitSubscriptionRequest}
                  style={{
                    padding: '10px 24px',
                    background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
                    border: 'none',
                    borderRadius: '8px',
                    color: 'white',
                    fontWeight: '600',
                    cursor: subscriptionRequestModal.loading || !subscriptionRequestModal.price || !subscriptionRequestModal.file ? 'not-allowed' : 'pointer',
                    opacity: subscriptionRequestModal.loading || !subscriptionRequestModal.price || !subscriptionRequestModal.file ? 0.6 : 1
                  }}
                >
                  {subscriptionRequestModal.loading ? '🚀 Submitting...' : '📤 Submit Renewal Request'}
                </button>
              </div>
            </div>
          </div>
        </div>
      ) : null}

      {feeRequestModal.open ? (
        <div className="modal-overlay">
          <div className="modal-content" style={{
            maxWidth: 800,
            borderRadius: '16px',
            background: 'white',
            boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
            border: 'none',
            overflowY: 'auto',
            maxHeight: '90vh',
            scrollbarWidth: 'none',
          }}>
            <div className="modal-header" style={{
              background: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
              color: 'white',
              padding: '20px 24px',
              borderBottom: 'none'
            }}>
              <h3 style={{ margin: 0, fontSize: '24px', fontWeight: '600' }}>
                🔍 Review Fee Payment Request
              </h3>
              <button
                className="close-btn"
                onClick={() => setFeeRequestModal({ open: false, request: null, remarks: '', saving: false })}
                style={{
                  background: 'rgba(255,255,255,0.2)',
                  border: 'none',
                  borderRadius: '50%',
                  width: '32px',
                  height: '32px',
                  color: 'white',
                  fontSize: '18px',
                  cursor: 'pointer'
                }}
              >
                ×
              </button>
            </div>
            <div style={{ padding: '24px' }}>
              {/* Status Badge */}
              <div style={{
                display: 'inline-block',
                padding: '6px 12px',
                background: '#fef3c7',
                color: '#92400e',
                borderRadius: '20px',
                fontSize: '12px',
                fontWeight: '600',
                marginBottom: '20px'
              }}>
                ⏳ PENDING REVIEW
              </div>

              {/* Student and Transaction Info */}
              <div style={{
                display: 'grid',
                gridTemplateColumns: '1fr 1fr',
                gap: '20px',
                marginBottom: '24px'
              }}>
                <div style={{
                  background: '#f8fafc',
                  padding: '16px',
                  borderRadius: '12px',
                  border: '1px solid #e2e8f0'
                }}>
                  <div style={{ fontSize: '13px', color: '#64748b', marginBottom: '4px' }}>
                    👤 Student Name
                  </div>
                  <div style={{ fontSize: '16px', fontWeight: '600', color: '#1f2937' }}>
                    {feeRequestModal.request?.student_name || 'N/A'}
                  </div>
                </div>
                <div style={{
                  background: '#f8fafc',
                  padding: '16px',
                  borderRadius: '12px',
                  border: '1px solid #e2e8f0'
                }}>
                  <div style={{ fontSize: '13px', color: '#64748b', marginBottom: '4px' }}>
                    💳 Transaction ID
                  </div>
                  <div style={{ fontSize: '16px', fontWeight: '600', color: '#1f2937' }}>
                    {feeRequestModal.request?.transaction_id || 'N/A'}
                  </div>
                </div>
              </div>

              {/* Screenshot Section */}
              <div style={{ marginBottom: '24px' }}>
                <div style={{
                  fontSize: '16px',
                  fontWeight: '600',
                  color: '#374151',
                  marginBottom: '12px'
                }}>
                  📸 Payment Screenshot
                </div>
                {feeRequestModal.request?.screenshot_url || feeRequestModal.request?.screenshot ? (
                  <div style={{
                    border: '1px solid #e2e8f0',
                    borderRadius: '12px',
                    overflow: 'hidden',
                    background: '#f8fafc'
                  }}>
                    <img
                      src={resolveMediaUrl(feeRequestModal.request.screenshot_url || feeRequestModal.request.screenshot)}
                      alt="Payment screenshot"
                      style={{
                        width: '100%',
                        maxHeight: '400px',
                        objectFit: 'contain',
                        cursor: 'pointer',
                        display: 'block'
                      }}
                      onClick={() => setLightboxImage(resolveMediaUrl(feeRequestModal.request.screenshot_url || feeRequestModal.request.screenshot))}
                    />
                  </div>
                ) : (
                  <div style={{
                    padding: '40px',
                    textAlign: 'center',
                    background: '#f8fafc',
                    border: '2px dashed #cbd5e1',
                    borderRadius: '12px',
                    color: '#64748b'
                  }}>
                    📷 No screenshot uploaded
                  </div>
                )}
              </div>

              {/* Remarks Section */}
              <div style={{ marginBottom: '24px' }}>
                <label style={{
                  display: 'block',
                  fontSize: '16px',
                  fontWeight: '600',
                  color: '#374151',
                  marginBottom: '8px'
                }}>
                  📝 Review Notes (Optional)
                </label>
                <textarea
                  value={feeRequestModal.remarks}
                  onChange={(e) => setFeeRequestModal((p) => ({ ...p, remarks: e.target.value }))}
                  className="input-field"
                  placeholder="Add notes for approval/rejection reason..."
                  rows={3}
                  style={{
                    width: '100%',
                    padding: '12px',
                    border: '1px solid #d1d5db',
                    borderRadius: '8px',
                    fontSize: '14px',
                    resize: 'vertical'
                  }}
                />
              </div>

              {/* Action Buttons */}
              <div style={{
                display: 'flex',
                gap: '12px',
                justifyContent: 'flex-end',
                paddingTop: '20px',
                borderTop: '1px solid #e2e8f0'
              }}>
                <button
                  className="btn"
                  onClick={() => setFeeRequestModal({ open: false, request: null, remarks: '', saving: false })}
                  style={{
                    padding: '12px 20px',
                    border: '1px solid #d1d5db',
                    background: 'white',
                    borderRadius: '8px',
                    cursor: 'pointer',
                    fontWeight: '500'
                  }}
                >
                  Cancel
                </button>
                <button
                  className="btn btn-danger"
                  disabled={feeRequestModal.saving}
                  onClick={() => reviewFeePaymentRequest('rejected')}
                  style={{
                    padding: '12px 24px',
                    background: 'linear-gradient(135deg, #ef4444 0%, #dc2626 100%)',
                    border: 'none',
                    borderRadius: '8px',
                    color: 'white',
                    fontWeight: '600',
                    cursor: feeRequestModal.saving ? 'not-allowed' : 'pointer',
                    opacity: feeRequestModal.saving ? 0.6 : 1
                  }}
                >
                  {feeRequestModal.saving ? '⏳ Processing...' : '❌ Reject Payment'}
                </button>
                <button
                  className="btn btn-success"
                  disabled={feeRequestModal.saving}
                  onClick={() => reviewFeePaymentRequest('approved')}
                  style={{
                    padding: '12px 24px',
                    background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
                    border: 'none',
                    borderRadius: '8px',
                    color: 'white',
                    fontWeight: '600',
                    cursor: feeRequestModal.saving ? 'not-allowed' : 'pointer',
                    opacity: feeRequestModal.saving ? 0.6 : 1
                  }}
                >
                  {feeRequestModal.saving ? '⏳ Processing...' : '✅ Approve Payment'}
                </button>
              </div>
            </div>
          </div>
        </div>
      ) : null}

      {deleteModal.show && (
        <div className="modal-overlay delete-modal-overlay">
          <div className="delete-modal">
            <h4 className="delete-modal-title">Delete Message?</h4>
            <div className="delete-modal-options">
              {deleteModal.canDeleteEveryone && (
                <button className="delete-option delete-everyone" onClick={() => handleDeleteConfirmed('everyone')}>Delete for everyone</button>
              )}
              <button className="delete-option delete-for-me" onClick={() => handleDeleteConfirmed('me')}>Delete for me</button>
              <button className="delete-option cancel-option" onClick={() => setDeleteModal({ show: false, ids: [], canDeleteEveryone: false })}>Cancel</button>
            </div>
          </div>
        </div>
      )}

      {false && lightboxImage && (
        <div className="lightbox-overlay" onClick={() => setLightboxImage(null)}>
          <div className="lightbox-content" onClick={e => e.stopPropagation()}>
            <button className="lightbox-close" onClick={() => setLightboxImage(null)}><FaTimes /></button>
            <img src={lightboxImage} alt="Preview" className="lightbox-image" />
            <button onClick={() => saveFile(lightboxImage)} className="lightbox-download-btn">
              <FaDownload /> Save Image
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default AdminDashboard;
